[theme]
primaryColor = "#2e7bb4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"

[server]
maxUploadSize = 200
enableCORS = false

[browser]
gatherUsageStats = false